# Generated by Django 4.2.4 on 2023-09-15 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_recipe_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cover',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='recipes/covers/%Y/%m/%d/'),
        ),
    ]
